import React from 'react';import {ArrowRight,MapPin,Play,Search,ShieldCheck,Sparkles} from 'lucide-react';import {motion} from 'framer-motion';import {Link} from 'react-router-dom';import {Button,NGOCard,ProjectCard,SectionHead,Stat} from '../App';import {causes,ngos,projects,stories} from '../data';
const causeImg=['https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=600&q=80','https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=600&q=80','https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&w=600&q=80','https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=600&q=80'];
const ngoImg=['https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=400&q=80','https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=400&q=80','https://images.unsplash.com/photo-1524749292158-7540c2494485?auto=format&fit=crop&w=400&q=80'];
const storyImg=['https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=700&q=80','https://images.unsplash.com/photo-1509099836639-18ba1795216d?auto=format&fit=crop&w=700&q=80','https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=700&q=80'];
export default function Home(){return <main>
<section className="hero"><div className="hero-copy"><div className="eyebrow">EVERY NGO IN INDIA. ONE PLATFORM.</div><h1>Find. Donate. <em>Directly.</em></h1><p>Search every verified NGO in India, see exactly what each one needs right now, and donate straight to their cause — no middlemen, all in one place.</p><div className="actions"><Button to="/ngos">Find an NGO to support</Button><Link className="text-link" to="/projects">See active projects <ArrowRight size={17}/></Link></div></div><div className="hero-art"><div className="hero-photo photo-a" style={{backgroundImage:'url(https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=900&q=80)'}}/><div className="hero-photo photo-b" style={{backgroundImage:'url(https://images.unsplash.com/photo-1509099836639-18ba1795216d?auto=format&fit=crop&w=700&q=80)'}}/><div className="floating-card"><ShieldCheck/><div><b>2,500+</b><span>NGOs you can search & donate to</span></div></div><div className="floating-tag">Local action <Sparkles size={14}/></div></div></section>
<section className="impact-strip"><Stat value="2,500+" label="verified / listed NGOs"/><Stat value="75" label="cause areas"/><Stat value="150+" label="districts & cities"/><Stat value="₹42 Cr" label="impact tracked"/><Stat value="50K+" label="volunteer profiles"/></section>
<section className="section"><SectionHead eyebrow="01 / CAUSES" title="Find the issue that moves you." text="Explore community work by the problems it solves—not by a wall of generic categories."/><div className="cause-grid">{causes.map((c,i)=><Link to={`/causes#${c.id}`} className={`cause-tile ${c.tone}`} key={c.id}><span>{String(i+1).padStart(2,'0')}</span><div><div className="cause-photo" style={{backgroundImage:`url(${causeImg[i%causeImg.length]})`}}/><small>{c.tag}</small><h3>{c.name}</h3><p>{c.text}</p><b>{c.count} <ArrowRight size={16}/></b></div></Link>)}</div></section>
<section className="section dark-section"><SectionHead light eyebrow="02 / THE NETWORK" title="One platform for every NGO in India." text="Search any NGO by cause or city, see their live needs, and send your donation straight to them — nothing scattered across a hundred websites."/><div className="steps"><div><span>01</span><h3>Search</h3><p>Find any NGO in India by cause, city or name in seconds.</p></div><div><span>02</span><h3>See their need</h3><p>Every NGO profile shows exactly what they need right now — funds, goods or volunteers.</p></div><div><span>03</span><h3>Donate directly</h3><p>Send support straight to the organisation, and track the outcome instead of just the receipt.</p></div></div></section>
<section className="section"><SectionHead eyebrow="03 / ACTIVE PROJECTS" title="Good work, made visible." text="A live view of projects that need people, resources and attention."/><div className="project-feature"><ProjectCard p={projects[0]} large/><div className="feature-copy"><span className="eyebrow">FEATURED PROJECT</span><h3>Small infrastructure. Long-term opportunity.</h3><p>Give students in 20 villages access to practical science learning, mentors and the tools to build their next step.</p><Button to="/projects">View all projects</Button></div></div></section>
<section className="section paper-2"><SectionHead eyebrow="04 / VERIFIED NETWORK" title="Every NGO's current need, in one place." text="Browse verified organisations and donate directly to the ones whose work matches what you care about."/><div className="card-grid">{ngos.slice(0,3).map((n,i)=><NGOCard key={n.name} n={{...n,img:ngoImg[i%ngoImg.length]}}/>)}</div><div className="center"><Button to="/ngos">Search all NGOs</Button></div></section>
<section className="map-section"><div><span className="eyebrow">05 / IMPACT MAP</span><h2>Impact is local. The network is connected.</h2><p>From Chennai to Cuddalore, Salem to Coimbatore, map the organisations and projects working close to the communities they serve.</p><Button to="/ngos">Open impact map</Button></div><div className="india-map"><span className="dot d1"/><span className="dot d2"/><span className="dot d3"/><span className="dot d4"/><span className="dot d5"/><div className="map-label"><MapPin size={15}/>150+ districts</div></div></section>
<section className="section stories-home"><SectionHead eyebrow="06 / FIELD NOTES" title="Stories behind the numbers."/><div className="story-grid">{stories.map((s,i)=><article className={i===0?'story featured':'story'} key={s.title}><div className="story-photo" style={{backgroundImage:`url(${storyImg[i%storyImg.length]})`}}/><span>{s.type}</span><h3>{s.title}</h3><p>{s.text}</p><b>{s.place} <ArrowRight size={15}/></b></article>)}</div></section>
<section className="cta"><span className="eyebrow">START SMALL. STAY CONSISTENT.</span><h2>You don't have to change the world.<br/><em>Start with one community.</em></h2><Button to="/register">Join ImpactGrid</Button></section>
</main>}
